trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

jobs:
- job: BuildAndScan
  displayName: 'Build Docker image, perform vulnerability scan, linting, and formatting'
  steps:

  # Step 1: Cache Trivy database to avoid downloading it every time
  - task: Cache@2
    inputs:
      key: 'trivy-db-$(Agent.OS)-$(Build.SourceBranchName)'
      restoreKeys: |
        trivy-db-$(Agent.OS)-
      path: ~/.cache/trivy

  # Step 2: Install necessary tools (Trivy, flake8, black)
  - script: |
      sudo apt-get update
      sudo apt-get install -y wget
      wget https://github.com/aquasecurity/trivy/releases/download/v0.38.0/trivy_0.38.0_Linux-64bit.deb
      sudo dpkg -i trivy_0.38.0_Linux-64bit.deb
      python3 -m pip install --upgrade pip
      python3 -m pip install flake8 black
    displayName: 'Install Trivy, flake8, and black'

  # Step 3: Refresh the Trivy DB to ensure it's up-to-date
  - script: |
      trivy --refresh
    displayName: 'Refresh Trivy DB'

  # Step 4: Run Linting (flake8)
  - script: |
      flake8 . --max-line-length=88
    displayName: 'Run flake8 Linting'
    continueOnError: true  # Continue the pipeline if linting issues are found

  # Step 5: Run Code Formatting (black)
  - script: |
      black --check --diff .
    displayName: 'Run black Formatting Check'
    continueOnError: true  # Continue the pipeline if formatting issues are found

  # Step 6: Build Docker image
  - task: Docker@2
    displayName: 'Build Docker image'
    inputs:
      command: 'build'
      containerRegistry: 'yourContainerRegistry'  # Replace with your registry
      repository: 'yolo_on_edge'
      dockerfile: '**/Dockerfile'  # Assuming Dockerfile is at the root
      tags: '$(Build.BuildId)'

  # Step 7: Perform the Trivy security scan with cached DB
  - script: |
      trivy fs --severity HIGH,CRITICAL --exit-code 1 .  # Scan for high and critical vulnerabilities
    displayName: 'Run Trivy Security Scan'
    continueOnError: true  # To allow the pipeline to continue even if the scan fails