name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Trigger on push to main branch
  pull_request:
    branches:
      - main  # Trigger on PR to main branch

jobs:
  security-check:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Install Trivy (Security Scanner)
      run: |
        curl -sfL https://github.com/aquasecurity/trivy/releases/download/v0.25.0/trivy_0.25.0_Linux-64bit.deb -o trivy.deb
        sudo dpkg -i trivy.deb

    - name: Run Trivy Security Scan
      run: |
        trivy fs --severity HIGH,CRITICAL --exit-code 1 .  # Scans the Dockerfile and the entire directory for vulnerabilities
      continue-on-error: false  # Ensure pipeline fails on security issues

  docker-build:
    runs-on: ubuntu-latest
    needs: security-check  # Ensure security check runs first

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      run: |
        docker buildx create --use  # Enable advanced build options
        docker buildx ls  # Verify setup

    - name: Build Docker Image
      run: |
        docker build -t yolov5-object-detection:$(date +'%Y%m%d%H%M%S') .  # Tag image with timestamp
      env:
        DOCKER_BUILDKIT: 1  # Enable BuildKit for Docker
